/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Conduit API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.github.jmlb23.mediumclone.data.models

data class UserResponse(
    var user: User
)
